# Ralph configuration — generated by `ralph init`. Edit freely; re-running
# `ralph init` will not overwrite this file.

# Commands Ralph runs locally before opening a PR. Empty string means
# "skip" (or, for INSTALL_CMD, the value the orchestrator prompt will ask
# Claude to figure out at runtime).
INSTALL_CMD="{{INSTALL_CMD}}"
TEST_CMD="{{TEST_CMD}}"
LINT_CMD="{{LINT_CMD}}"

# Coding agent Ralph drives. "claude" (default) uses Claude Code; "codex" uses
# the OpenAI Codex CLI. Unset or unrecognized falls back to "claude". Nothing
# else in this file changes between agents.
RALPH_AGENT="{{RALPH_AGENT}}"

# Task source Ralph pulls work from. "github" (default) resolves open GitHub
# issues via `gh`; "folder" draws tasks from the local `.ralph/tasks/` tree and
# commits straight to DEV_BRANCH (no PR/merge). Unset falls back to "github".
TASK_SOURCE="{{TASK_SOURCE}}"

# Model id for the Codex agent (ignored when RALPH_AGENT=claude). Leave
# unset/commented to let Codex use its configured default. Example:
# RALPH_CODEX_MODEL="gpt-5-codex"
# RALPH_CODEX_MODEL=""

# Branches. Autodetected from `origin/HEAD` and `git branch -a`.
MAIN_BRANCH="{{MAIN_BRANCH}}"
DEV_BRANCH="{{DEV_BRANCH}}"
PR_TARGET="{{PR_TARGET}}"

# PR merge behavior.
MERGE_STRATEGY="squash"
AUTO_MERGE="true"
MERGE_POLL_INTERVAL=30
MERGE_POLL_MAX=40

# Context-window override (tokens) for end-of-job occupancy metrics. Leave
# unset/empty to auto-resolve from the run's model id (opus/sonnet/fable =
# 1_000_000, haiku = 200_000; default 1_000_000 for the opus family). Set a
# positive integer to override, e.g. RALPH_CONTEXT_WINDOW=200000 for a 200k
# model. A non-numeric or <= 0 value is ignored.
# RALPH_CONTEXT_WINDOW=1000000

# Per-issue effort tiering (dark-launch foundation). Gates the Tier 2 /
# Heavy triage path. 0 = off (the default): the heavy tier is unavailable
# and triage falls back to Tier 1, so behavior is unchanged.
RALPH_HEAVY_TIER=0
