# Ralph configuration — generated by `ralph init`. Edit freely; re-running
# `ralph init` will not overwrite this file.

# Commands Ralph runs locally before opening a PR. Empty string means
# "skip" (or, for INSTALL_CMD, the value the orchestrator prompt will ask
# Claude to figure out at runtime).
INSTALL_CMD="{{INSTALL_CMD}}"
TEST_CMD="{{TEST_CMD}}"
LINT_CMD="{{LINT_CMD}}"

# Coding agent Ralph drives. "claude" (default) uses Claude Code; "codex" uses
# the OpenAI Codex CLI. Unset or unrecognized falls back to "claude" and warns on
# stderr — `ralph start` says so once, above the banner, and the loop says it again in
# its own window — so a typo here costs you a line of output and never the run. A
# recognized value prints nothing. Nothing else in this file changes between agents.
#
# The loop SOURCES this file with `set -a`, so a value here beats one exported in your
# shell — and a blank RALPH_AGENT="" is a value rather than an absence: it means
# "claude", not "whatever was inherited". `ralph start` reports on the same rule, so its
# banner never names an agent the loop is not about to run.
RALPH_AGENT="{{RALPH_AGENT}}"

# Task source Ralph pulls work from. "github" (default) resolves open GitHub
# issues via `gh`; "folder" draws tasks from the local `.ralph/tasks/` tree and
# commits straight to DEV_BRANCH (no PR/merge). Unset falls back to "github".
#
# "jira" is the third value, and it is NOT A WHOLE LOOP YET — but it now does the
# work. Each iteration COUNTS, SELECTS and CLAIMS from your Jira project (see JIRA_JQL
# below): it takes the oldest eligible ticket, records it as the task in flight, adds
# the `in-progress` label — the label the query excludes, so the queue drains — and
# then INVOKES THE AGENT on that ticket. The agent is handed the KEY and reads the work
# item itself through `acli`, then resolves it and commits straight to DEV_BRANCH with
# the key in the commit message: no branch, no PR, no merge, the same delivery shape as
# the folder source. The loop runs no `gh` command at all under this value.
#
# WHAT IS MISSING IS THE BOOKKEEPING, at both ends. THE COMMIT STAYS LOCAL: nothing in
# the loop pushes it, so `git log DEV_BRANCH` on the machine that ran Ralph is the only
# place that work exists. And nothing is written back to the board: no transition to a
# done status, no done label, no comment carrying the commit SHA, and no `failed` label
# on an iteration that produced nothing. THE COMMANDS THAT START THE LOOP have NOT moved
# with it either, and BOTH of them still want `gh`: `ralph start` and `ralph cycle` each
# abort unless `gh auth status` succeeds, however little the run itself uses it. On top of
# that, `ralph start` still counts GitHub issues to decide whether to launch — so its
# number can differ from `ralph status`'s, and an empty GitHub queue stops a launch that
# had Jira tickets waiting. `ralph cycle` is the one that already counts Jira, like
# `ralph status`. So a jira repo still needs `gh` installed and logged in, even though
# `ralph doctor` no longer lists it here.
#
# THE CLAIM IS A WRITE TO YOUR BOARD AND NOTHING TAKES IT BACK: no Ralph command ever
# removes `in-progress` again. That write is what drains the queue rather than handing
# the same ticket out forever, so it is not incidental — but with no completion
# bookkeeping, one pass over your whole eligible queue leaves every ticket in it reading
# as in flight, and which of them were actually resolved is discoverable only from the
# local commits and the per-ticket logs (`logs/ralph-issue-<KEY>.log`). Ralph then reads
# that queue as empty until you strip the label yourself, in Jira. There is no Jira
# analog yet of the `claude-working` cleanup the github source does. So point a NARROW
# JIRA_JQL at this while it is half built.
#
# The prerequisites are checkable BEFORE they are needed. A jira run wants
# Atlassian's `acli` on PATH and an authenticated session (`acli jira auth login`),
# and `ralph doctor` reports both once this file says "jira": `acli` as a required
# dep with a per-platform install hint, and the login state as its own row
# (reported, never enforced — it cannot fail doctor). An `acli` that is missing,
# logged out, or answering something unparseable costs you the COUNT and never the
# run: the depth reads as zero (or as "unknown" in `ralph status`), so a cycle
# exits saying the queue is empty instead of failing. In the loop the same failure
# reads as an empty queue at SELECTION time (it stops, having worked nothing) and as
# a warning at CLAIM time (the ticket stays eligible and the loop moves on).
TASK_SOURCE="{{TASK_SOURCE}}"

# Jira eligibility query, used when TASK_SOURCE="jira" and ignored otherwise. ONE query
# answers both questions the source asks — how deep the queue is, and which ticket is
# next — so a count and a selection can never disagree about what is eligible. Write
# the half that is YOURS — which work items are candidates for Ralph — and nothing
# about labels or ordering:
#
# JIRA_JQL="project = RALPH AND statusCategory != Done AND assignee = currentUser()"
#
# RALPH APPENDS ITS OWN HALF and you cannot turn that off. Your clause is wrapped in
# parentheses (so an `OR` in it keeps its meaning against the `AND` that follows),
# then the exclusion `AND (labels NOT IN (in-progress, failed, do-not-ralph) OR
# labels IS EMPTY)` is added — the `IS EMPTY` half matters, because in JQL a
# `NOT IN` never matches a work item whose labels are unset, and without it a
# freshly filed unlabelled ticket would be invisible to Ralph. The exclusion is what
# keeps the loop off work already in flight, already failed, or marked hands-off — and
# its `in-progress` half is the very label the loop WRITES when it claims a ticket, so
# claiming is what makes the next pass skip it. One mechanism, not two conventions.
#
# ORDERING IS RELOCATED, NOT REFUSED. Jira requires ORDER BY to be the last clause,
# so if your query ends with one it is moved back to the end after the exclusion is
# inserted, exactly as you wrote it. Write no ORDER BY and you get `ORDER BY created
# ASC` — oldest first, the same rule github mode uses, so the queue drains rather
# than churning on whatever was filed last.
#
# EMPTY MEANS NOT CONFIGURED, and it is deliberately not "everything": a query of
# Ralph's half alone would select every work item on the Jira site and report a queue
# depth that belongs to somebody else's board. So an empty value counts nothing, selects
# nothing, runs no `acli`, and `ralph status` says the queue depth is unknown; a loop
# started with it exits "Queue empty" on its first pass.
#
# A `#` ANYWHERE IN YOUR QUERY NEEDS SINGLE QUOTES — searching for a ticket reference
# (`summary ~ "#123"`) is the case that hits this. Ralph reads this file without sourcing
# it, and that reader closes a double-quoted value at an inner quote and takes a `#` after
# it for a comment, so JIRA_JQL="summary ~ \"#123\"" reaches Jira truncated: the query is
# rejected, and a rejected query costs you the count silently (the depth reads as zero, so
# a cycle says the queue is empty). Either spelling avoids it — quote the VALUE with single
# quotes, JIRA_JQL='summary ~ "#123"', or write the JQL literal with them,
# JIRA_JQL="summary ~ '#123'". A query with no `#` in it is unaffected.
JIRA_JQL=""

# How much of the startup banner `ralph start` draws. "full" (the default) plays the
# one-second sprite splash, settles on its final frame, and prints the identity box
# under it. "static" draws the same picture with none of the animation — the settled
# frame, once, in a single write. "off" prints nothing at all, not even the box. Unset
# or empty means "full"; an unrecognized value also means "full" and warns on stderr,
# so a typo here costs you a line of output and never the run.
#
# The terminal only ever caps this DOWNWARD. A pipe, a launchd log, a NO_COLOR run or a
# window narrower than the sprite draws no sprite whatever this says — and still prints
# the box, because a log is exactly where "which version, which directory" is the
# question being asked. Only an explicit "off" takes the box away.
#
# An environment variable of the same name WINS over this line, which is deliberately
# the opposite of TASK_SOURCE above: a task source is a property of the repo, a banner
# is a property of one invocation. So `RALPH_BANNER=off ralph start` silences a single
# run inside a wrapper script, a cron entry or a CI job without editing a committed
# file that every other run in this repo shares.
RALPH_BANNER="full"

# Model id for the Codex agent (ignored when RALPH_AGENT=claude). Leave
# unset/commented to let Codex use its configured default. Example:
# RALPH_CODEX_MODEL="gpt-5-codex"
# RALPH_CODEX_MODEL=""

# How often the digest runs while the loop works. A digest is a few sentences of
# prose about what is happening right now (`ralph digest`), from a cheap model
# with no tools. Set an interval and `ralph start` opens a second tmux window
# named `digest` next to the loop, running `ralph digest --loop` on that interval
# and printing each one into the pane; `ralph stop` takes it down with the rest
# of the session. Empty or 0 DISABLES it — the default, so nothing here costs a
# model call until you ask for one. Accepts the same durations as `ralph schedule
# install --interval`: 60 (seconds), 30m, 2h, 1d — a whole number and at most one
# unit letter, so 0.5h is refused, as is anything over 24d (longer than a timer
# can wait). A refused value costs you the digest and not the run: `ralph start`
# warns on stderr, says NOT running in its launch box, and starts the loop
# anyway. 30m suits tasks that take 40-100 minutes; there is no point narrating
# faster than the work changes.
RALPH_DIGEST_INTERVAL=""

# Model the digest asks. Leave unset/commented for the cheap default (haiku under
# RALPH_AGENT=claude, gpt-5-mini under codex) — this is narration, not the work,
# and the loop's own model is chosen for depth. `ralph start` forwards this value
# into the digest window it opens (along with RALPH_AGENT), so an unattended digest
# uses the model this repo committed to rather than whatever the launching shell
# happened to export; for a digest you run by hand, export it or set it inline.
# Example:
# RALPH_DIGEST_MODEL="haiku"

# Branches. Autodetected from `origin/HEAD` and `git branch -a`.
MAIN_BRANCH="{{MAIN_BRANCH}}"
DEV_BRANCH="{{DEV_BRANCH}}"
PR_TARGET="{{PR_TARGET}}"

# PR merge behavior.
MERGE_STRATEGY="squash"
AUTO_MERGE="true"
MERGE_POLL_INTERVAL=30
MERGE_POLL_MAX=40

# Context-window override (tokens) for end-of-job occupancy metrics. Leave
# unset/empty to auto-resolve from the run's model id (opus/sonnet/fable =
# 1_000_000, haiku = 200_000; default 1_000_000 for the opus family). Set a
# positive integer to override, e.g. RALPH_CONTEXT_WINDOW=200000 for a 200k
# model. A non-numeric or <= 0 value is ignored.
# RALPH_CONTEXT_WINDOW=1000000

# Per-issue effort tiering (dark-launch foundation). Gates the Tier 2 /
# Heavy triage path. 0 = off (the default): the heavy tier is unavailable
# and triage falls back to Tier 1, so behavior is unchanged.
RALPH_HEAVY_TIER=0
